### PR TITLE
Made hostName available as a parameter for startNotifier

### PR DESCRIPTION
**Pull request by kpbode**
I just added NSString *hostName and added a static variable for the hostname as with the options for useSSL etc. The notifier falls back to the host defined in ABNotifierHostName if not passed in.

### CODE REVIEW

**Comment by kyrylo** [comment]
@jocelynlih could you please take a look?

**Comment by jocelynlih** [comment]
@kyrylo this seems like a feature we can add for the next release. There is some conflict but should be easy to fix.

**Comment by kyrylo** [comment]
@jocelynlih could you please resolve those conflicts (perhaps in a separate commit or in any way you prefer) and make a new release? :P

**Comment by jocelynlih** [comment]
Yep, will do.

**Pull request merged**
